# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  EasyGL_config = debug
  Sandbox_config = debug

else ifeq ($(config),release)
  EasyGL_config = release
  Sandbox_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := EasyGL Sandbox

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

EasyGL:
ifneq (,$(EasyGL_config))
	@echo "==== Building EasyGL ($(EasyGL_config)) ===="
	@${MAKE} --no-print-directory -C . -f EasyGL.make config=$(EasyGL_config)
endif

Sandbox:
ifneq (,$(Sandbox_config))
	@echo "==== Building Sandbox ($(Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C . -f Sandbox.make config=$(Sandbox_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f EasyGL.make clean
	@${MAKE} --no-print-directory -C . -f Sandbox.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   EasyGL"
	@echo "   Sandbox"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"